FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

WORKDIR /app

# Устанавливаем uv
COPY --from=ghcr.io/astral-sh/uv:0.10.0 /uv /uvx /bin/

# Сначала копируем файлы зависимостей
# Это позволяет Docker использовать cache
COPY pyproject.toml uv.lock ./

# Устанавливаем зависимости вместе с uvicorn
RUN uv sync --frozen

# Копируем исходный код
COPY app ./app
COPY alembic ./alembic
COPY alembic.ini ./

EXPOSE 8000

# Development server
CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port",  "8000", "--reload"]